version: '3.8'

services:
  db:
    image: postgres:16
    container_name: contacts-db
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contacts-network

  app:
    build: .
    container_name: contacts-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contacts
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8080:8080"
    networks:
      - contacts-network

volumes:
  postgres_data:

networks:
  contacts-network:
    driver: bridge
