package com.example.contactsrest.models;

import jakarta.persistence.*;

@Entity //This marks the next class as an entity
@Table(name = "contacts") //This will map the next class as a table named "contacts" in the db
public class ContactModel {
    @Id //This will specify the next property as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // This will specify that the primary key values are automatically generated by the database
    @Column(unique = true, nullable = false)
    private Long id;
    private String name;
    private String phoneNumber;
    private String email;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
